from enum import Enum

class ChatSummaryTopics(Enum):
  LIFE_GOALS_VALUES = "life-goals-and-values"
  USER_PERSONALITY_AND_TRAITS = "user-personality-and-traits"
  PARTNER_CRITERIA = "partner-criteria"
  HOBBIES_MOVIES = "hobbies-movies"
  HOBBIES_EXERCISE = "hobbies-exercise"
  HOBBIES_ART = "hobbies-art"
  HOBBIES_TECHNOLOGY = "hobbies-technology"
  HOBBIES_CAREER = "hobbies-career"
  HOBBIES_COFFEE = "hobbies-coffeee"
  HOBBIES_MUSIC = "hobbies-music"
  HOBBIES_BOOKS = "hobbies-books"
  HOBBIES_PET = "hobbies-pet"
  HOBBIES_TRAVELING = "hobbies-traveling"
  HOBBIES_PHOTOGRAPHY = "hobbies-photography"
  HOBBIES_WRITING = "hobbies-writing"
  HOBBIES_DANCE = "hobbies-dance"
  HOBBIES_GAMING = "hobbies-gaming"
  HOBBIES_COOKING = "hobbies-cooking"
  HOBBIES_FOODS = "hobbies-food"
  HOBBIES_GARDENING = "hobbies-gardening"
  HOBBIES_YOGA = "hobbies-yoga"