name: Hello World!

on:
  push:
    branches:
      - build/ci-cd

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Print Date
        run: |
          date

      - name: Print Files
        run: |
          ls -l
